#!/usr/bin/env python
# coding=utf-8
# simple git update for mksec pulling from core modules
import os
import sys

# check where we are and load default directory
if os.path.isdir("/usr/share/mksec"):
    if not os.path.isfile("mksec"):
        os.chdir("/usr/share/mksec")
        sys.path.append("/usr/share/mksec")

import src.core.core_mksec as core

# if we can't see our config then something didn't go good...
if not os.path.isfile("/etc/mksec/set.config"):
    core.print_error("Cannot locate MKSEC executable. Try running from the local directory.")
    core.print_error("If this does not work, please run the setup.py install file.")
    sys.exit()

try:
    # pull update set from the core libraries
    core.update_set()

# except keyboard interrupts
except KeyboardInterrupt:
    print("\n[!] Control-C detected. Exiting updating MKSEC.")

# handle all other errors
except Exception as e:
    print("\n[!] Something went wrong.. Printing the error: {0}".format(e))
